services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-todo-api
    volumes:
      - ./config.json:/app/config.json  
      - ./db/migrations:/app/db/migrations 
    ports:
      - "9090:9090"   
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - go-network

  postgres:
    image: postgres:15
    container_name: go-todo-api-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rangga
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - go-network

  redis:
    image: redis:7
    container_name: go-todo-api-redis
    ports:
      - "6379:6379"
    networks:
      - go-network

volumes:
  db_data:

networks:
  go-network:
    driver: bridge
