version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-api
    container_name: go-todo-api
    ports:
      - 9090:9090
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/build/app  # Pastikan volume cocok dengan struktur proyek

  postgres:
    image: postgres:15
    container_name: go-api-learn-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo_db  
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

volumes:
  database_dockerizing:
