services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-todo-api
    volumes:
      - ./config.json:/app/config.json   
    ports:
      - "9090:9090"   
    environment:
      - SERVER_ADDRESS = ":9090"
      - CONTEXT_TIMEOUT = 2
      - DATABASE_HOST = "localhost"
      - DATABASE_PORT = "5432"
      - DATABASE_USER = "postgres"
      - DATABASE_PASS = rangga
      - DATABASE_NAME = "todo_db"
      - JWT_SECRET_KEY = "private-key"
      - JWT_EXPIRATION_TIME = 3
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - go-network

  postgres:
    image: postgres:15
    container_name: go-todo-api-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rangga
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - go-network

volumes:
  db_data:

networks:
  go-network:
